# Generated by Django 6.0.4 on 2026-04-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('año', models.PositiveIntegerField(default=2026)),
                ('potencia_hp', models.IntegerField(verbose_name='Potencia (HP)')),
                ('traccion', models.CharField(choices=[('4x2', '4x2'), ('4x4', '4x4')], max_length=20)),
                ('transmision', models.CharField(max_length=200)),
                ('motor', models.CharField(max_length=200)),
                ('estado_stock', models.CharField(choices=[('disponible', 'Stock Inmediato'), ('transito', 'En Tránsito (China)'), ('pedido', 'Bajo Pedido')], default='disponible', max_length=20)),
                ('precio_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Maquinarias',
            },
        ),
    ]
