# Generated by Django 6.0.4 on 2026-04-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='especificaciones_extra',
            field=models.TextField(blank=True, verbose_name='Especificaciones Técnicas'),
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='maquinaria/'),
        ),
    ]
