# Generated by Django 6.0.4 on 2026-04-20 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_maquinaria_especificaciones_extra_maquinaria_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('mensaje', models.TextField(blank=True)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('maquina_interes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.maquinaria', verbose_name='Unidad de Interés')),
            ],
            options={
                'verbose_name': 'Consulta de Cliente',
                'verbose_name_plural': 'Consultas de Clientes',
            },
        ),
    ]
