# Generated by Django 5.2.7 on 2026-04-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo / Puesto'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='codigo_seguimiento',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True, verbose_name='N° Seguimiento'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='rubro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rubro / Sector'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='mensaje',
            field=models.TextField(blank=True, verbose_name='Consulta Puntual'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='telefono',
            field=models.CharField(max_length=50, verbose_name='Teléfono / WhatsApp'),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
