# Generated by Django 5.2.7 on 2026-04-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_consulta_cargo_consulta_codigo_seguimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='nombre_imagen_local',
            field=models.CharField(blank=True, help_text='Ej: TL1404.png. Debe estar en inventario/static/inventario/img/', max_length=100, null=True, verbose_name='Nombre Imagen Local'),
        ),
    ]
