# Generated by Django 5.2.7 on 2026-04-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_maquinaria_nombre_imagen_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFinanciera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa BNA Dólares (%)')),
                ('tasa_pesos', models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='Tasa BNA Pesos (%)')),
                ('plazo_meses', models.IntegerField(default=60, verbose_name='Plazo Máximo (Meses)')),
                ('vigente', models.BooleanField(default=True, verbose_name='Promoción Vigente')),
            ],
            options={
                'verbose_name': 'Configuración Financiera BNA',
                'verbose_name_plural': 'Configuraciones Financieras BNA',
            },
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='apto_credito_bna',
            field=models.BooleanField(default=True, verbose_name='Apto Crédito BNA'),
        ),
    ]
