# Generated by Django 5.2.7 on 2026-04-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_configuracionfinanciera_maquinaria_apto_credito_bna'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('contactado', 'Contactado'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20, verbose_name='Estado de Gestión'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='observaciones_internas',
            field=models.TextField(blank=True, verbose_name='Observaciones Internas (Vendedores)'),
        ),
    ]
