# Generated by Django 5.2.7 on 2026-05-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_consulta_estado_consulta_observaciones_internas'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaVisita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, unique=True, verbose_name='Fecha')),
                ('contador', models.PositiveIntegerField(default=0, verbose_name='Visitas del Día')),
            ],
            options={
                'verbose_name': 'Estadística de Visita',
                'verbose_name_plural': 'Estadísticas de Visitas',
            },
        ),
        migrations.AlterField(
            model_name='configuracionfinanciera',
            name='tasa_pesos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa BNA Pesos (%)'),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='apto_credito_bna',
            field=models.BooleanField(default=False, verbose_name='Apto Crédito BNA'),
        ),
    ]
