# Generated by Django 5.2.7 on 2026-06-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_estadisticavisita_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45, verbose_name='Dirección IP')),
                ('path', models.CharField(max_length=255, verbose_name='Ruta Visitada')),
                ('user_agent', models.TextField(blank=True, verbose_name='Navegador/Dispositivo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Accesos',
                'ordering': ['-timestamp'],
            },
        ),
    ]
