# Generated by Django 5.2.7 on 2026-06-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_accesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45, unique=True, verbose_name='Dirección IP')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('provincia_estado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia/Estado')),
                ('pais', models.CharField(blank=True, max_length=100, null=True, verbose_name='País')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Caché de IP',
                'verbose_name_plural': 'Cachés de IPs',
            },
        ),
        migrations.AddField(
            model_name='consulta',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='IP del Cliente (Secreta)'),
        ),
    ]
