# Generated by Django 5.2.7 on 2026-06-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_ipcache_consulta_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadAdministrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255, verbose_name='Acción Realizada')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ruta Visitada')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
            ],
            options={
                'verbose_name': 'Actividad del Administrador',
                'verbose_name_plural': 'Actividad de Martino',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
